# _config.yml

title: PALISI BACON Subgroup
email: BaconStudy@nationwidechildrens.org
description: >
  Official website of the PALISI BACON Subgroup: a collaborative research group focused on bronchiolitis and pediatric viral lower respiratory tract infections.

# GitHub Pages settings
baseurl: "" # leave empty unless using a subfolder
url: "https://wenmd.github.io" 

# Theme and plugins
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown processing
markdown: kramdown
kramdown:
  input: GFM

# Output settings for blog posts (optional)
collections:
  posts:
    output: true
